/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lexical.analyzer.rotc;

/**
 *
 * @author PC
 */
public class Ouput extends javax.swing.JFrame {

    /**
     * Creates new form Ouput
     */
    public Ouput() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RunBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        SourceTxt = new javax.swing.JTextArea();
        ExitBtn = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        LexicalTbl = new javax.swing.JTable();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        ErrorTxt = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        RunBtn.setText("Run");
        RunBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RunBtnMouseClicked(evt);
            }
        });
        RunBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunBtnActionPerformed(evt);
            }
        });
        getContentPane().add(RunBtn);
        RunBtn.setBounds(15, 0, 93, 29);

        ClearBtn.setText("Clear");
        getContentPane().add(ClearBtn);
        ClearBtn.setBounds(123, 0, 100, 29);

        SourceTxt.setColumns(20);
        SourceTxt.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        SourceTxt.setRows(5);
        jScrollPane1.setViewportView(SourceTxt);

        jTabbedPane1.addTab("Source", jScrollPane1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 38, 245, 145);

        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ExitBtn);
        ExitBtn.setBounds(290, 0, 113, 29);

        LexicalTbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LexicalTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Lexeme", "Token"
            }
        ));
        jScrollPane3.setViewportView(LexicalTbl);

        jTabbedPane2.addTab("Lexical Table", jScrollPane3);

        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(254, 38, 149, 271);

        ErrorTxt.setColumns(20);
        ErrorTxt.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        ErrorTxt.setRows(5);
        jScrollPane2.setViewportView(ErrorTxt);

        jTabbedPane3.addTab("Error List", jScrollPane2);

        getContentPane().add(jTabbedPane3);
        jTabbedPane3.setBounds(0, 199, 245, 110);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RunBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RunBtnMouseClicked
        // TODO add your handling code here

    }//GEN-LAST:event_RunBtnMouseClicked

    private void RunBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RunBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ouput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ouput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ouput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ouput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ouput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearBtn;
    private javax.swing.JTextArea ErrorTxt;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JTable LexicalTbl;
    private javax.swing.JButton RunBtn;
    private javax.swing.JTextArea SourceTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
